### ISSUE TITLE
Ruby 1.8.6 Issue

### ISSUE THREAD

**Issue by waynegraham** [mwmitchell/rsolr-ext#1]
Ok, at this point this is a legacy issue, but it should be probably be recorded...

There's a "feature" introduced in ruby 1.8.7 in the Fixnum.times from requiring a block (1.8.6) and accepting a block (1.8.7+). This was causing an issue on 1.8.6 instances in the facets and has been fixed and verified for 1.8.6.

**Comment by mwmitchell** [comment]
yep no longer an issue, but that was a tricky one.
