### ISSUE TITLE
facet limits

### ISSUE THREAD

**Issue by rb2k** [mwmitchell/rsolr-ext#2]
There is currently no way to actually set the "facet.limit" parameter when using facets

**Comment by mwmitchell** [comment]
This should work: rsolr_ext.find("facet.limit" => 5)

Can you give more info on how you're using rsolr-ext (setup, query, version) and what, if any, errors are coming up?

**Comment by rb2k** [comment]
thanks, that worked!
I tried putting it in the facet hash, that didn't work. maybe adding it to the documentation would be nice :)  
This question also had been asked on http://groups.google.com/group/rsolr/browse_thread/thread/eddf5bb5a52db79
