### ISSUE TITLE
update rsolr-ext to work with spellcheck format of the Solr 1.4 release

### ISSUE THREAD

**Issue by jronallo** [mwmitchell/rsolr-ext#3]
Between 1.3 and 1.4 the format of the spellcheck results changed some. Simple results are returned by default. There are several options that can now be added on to return extended suggestions which include the frequency and/or collated suggestions.

I have created a fork where spellcheck is now tested. The mocks were taken from variations on the Solr wiki and the example Solr data. (http://wiki.apache.org/solr/SpellCheckComponent)

You can see the commit here:
http://github.com/jronallo/rsolr-ext/commit/d208f62c4ad19731b86e7dd2e9fd714659846d55

We are trying to upgrade Blacklight from a 1.4 prerelease/nightly to the Solr 1.4.1 release. You can see our ticket for that work here:
http://jira.projectblacklight.org/jira/browse/CODEBASE-241

I'd like to get this integrated into trunk rsolr-ext and ask that a new tagged release is made. I've bumped the patch level, but you may want to choose a different version number.

Please let me know what else I can do to get these changes in. I'll be sending a pull request.

Jason

**Comment by mwmitchell** [comment]
This is great. Thanks for your work with this Jason. I applied the change and will release a new rsolr-ext ASAP.

Matt
