### ISSUE TITLE
simulates a will_paginate list insufficiently

### ISSUE THREAD

**Issue by jrochkind** [mwmitchell/rsolr-ext#9]
I THINK (correct me if I'm wrong) the array returned by a Solr fetch when using RSolr::Ext is supposed to be simulate the array returned by will_paginate's paginate, so you can just pass the returned array to will_paginate for pagination. 

In Blacklight we do pass in the returned array to will_paginate's methods, but we need to over-ride will_paginate's #page_entries_info to make it actually work with RSolr::Ext's results.  I thought we were just over-riding it to change the formatting of the display, but I think our over-ride actually uses different accessors on the collection result object too. 

The problem is, this means that once we've over-ridden it like this, you cant' use any of will_paginate's methods with anythign ELSE in that app, since #page_entries_info has been over-ridden to expect methods that are in RSolr::Ext's collection object, but NOT in will_paginate's own collection objects returned by #paginate. 

See the definition of #page_entries_info in will_paginate here:  https://github.com/mislav/will_paginate/blob/master/lib/will_paginate/view_helpers.rb

I was trying to return #page_entries_info in BL to a state where it'd reformat the string, sure, but still work with ordinary will_paginate collections too. But having trouble doing this, because I don't think RSolr::Ext's response object duck-types a will_paginate collection sufficiently. 

In particular, as you can see from the original page_entries_info definition, a will_paginate collection has an #offset and an a #total_entries.   But an RSolr::Ext does not.  So we instead have to over-ride page_entires_info to ask for different things that RSolr::Ext DOES have, in the process breaking it for anything else. 

(As a side comment relevant to BL but not neccesarily to RSolr -- the BL page_entries_info is looking at the @response instance variable instead of just the argument passed in, breaking it even MORE for any other use of will_paginate).

**Comment by jrochkind** [comment]
Looks like it MIGHT just be that will_paginate's collections have #total_entries, but RSolr::Ext::Response has only #total but not #total_entries.  Giving RSolr::Ext::Response #total_entries might be sufficient for my current problem. 

Although if you really want to duck-type a WillPaginate::Collection fully, there are a bunch of other methods you need, including #offset and maybe a couple others. https://github.com/mislav/will_paginate/blob/master/lib/will_paginate/collection.rb

**Comment by jrochkind** [comment]
I bet maybe will_paginate USED to call it's method #total instead?

Seems like if a RSolr::Ext::Response is supposed to act like a WillPaginate::Collection, when the latter's API isn't documented, the safest way would be to actually USE one.  Have Response sub-class a Collection, or have it delegate to one it actually instantiates.

**Comment by cbeer** [comment]
I've created a proposed pull request at https://github.com/mwmitchell/rsolr-ext/pull/11 that actually uses a WillPaginate::Collection.

**Comment by mwmitchell** [comment]
Yep this all makes sense. WillPaginate has definitely changed. I'll check out your patch cbeer. Thanks to you both!

**Comment by mwmitchell** [comment]
see https://github.com/mwmitchell/rsolr-ext/pull/11
